### ISSUE TITLE
ダークモード機能

### ISSUE THREAD

**Issue by Ota1022** [Ota1022/ota1022.github.io#2]

**Comment by minobun** [comment]
参照リンク
AppRouter利用時のMUI統合方法について：https://mui.com/material-ui/integrations/nextjs/#app-router
ContextProvider利用時のレンダリングについて：https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-context-providers
MUIのThemeをカスタマイズする際の注意点：https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-context-providers

**Comment by Ota1022** [comment]
Thank you for your contribution!! @minobun
